

export const OBSERVE_HEADLINE_MAX_CHARS = 120;
export const OBSERVE_DETAILS_MAX_CHARS = 8000;

export const OBSERVE_GOAL_TERMS_MAX_SOURCES_LIST = 10;

export const OBSERVE_ARTIFACT_MAX_CLAIMS = 5;
export const OBSERVE_CLAIM_SENTENCES_MAX = 10;
export const OBSERVE_CLAIM_LONG_SENTENCE_THRESHOLD = 80;

export const OBSERVE_HEURISTIC_BASE = 0.55;
export const OBSERVE_HEURISTIC_NUMERIC_BONUS = 0.08;
export const OBSERVE_HEURISTIC_GOAL_MATCH_BASE_BONUS = 0.05;
export const OBSERVE_HEURISTIC_GOAL_MATCH_EXTRA_BONUS = 0.01;
export const OBSERVE_HEURISTIC_GOAL_MATCH_MAX_BONUS = 0.10;
export const OBSERVE_HEURISTIC_HEDGING_PENALTY = 0.12;
export const OBSERVE_HEURISTIC_HYPE_PENALTY = 0.04;
export const OBSERVE_HEURISTIC_STRONG_VERB_BONUS = 0.04;
export const OBSERVE_HEURISTIC_SHORT_LEN_THRESHOLD = 40;
export const OBSERVE_HEURISTIC_SHORT_LEN_PENALTY = 0.04;
export const OBSERVE_HEURISTIC_LONG_LEN_THRESHOLD = 280;
export const OBSERVE_HEURISTIC_LONG_LEN_PENALTY = 0.04;
export const OBSERVE_HEURISTIC_STALE_YEAR_THRESHOLD = 3;
export const OBSERVE_HEURISTIC_STALE_YEAR_PENALTY = 0.05;

export const OBSERVE_HEURISTIC_MIN = 0.15;
export const OBSERVE_HEURISTIC_MAX = 0.95;
export const OBSERVE_HEURISTIC_KEEP_MIN = 0.18;

export const OBSERVE_CONFIDENCE_DECIMALS = 2;

export const OBSERVE_BLEND_DIVISOR = 2;

export const OBSERVE_LLM_CLAIM_SCORING_MAX_CLAIMS = 40;
export const OBSERVE_LLM_RATIONALE_MAX_CHARS = 160;

export const OBSERVE_ARTIFACT_SUMMARY_SNIPPET_CHARS = 800;
